version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env.mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge